;########### SECCION DE DATOS
section .data

;########### SECCION DE TEXTO (PROGRAMA)
section .text

; Completar las definiciones (serán revisadas por ABI enforcer):
USUARIO_ID_OFFSET EQU 0
USUARIO_NIVEL_OFFSET EQU 0
USUARIO_SIZE EQU 0

CASO_CATEGORIA_OFFSET EQU 0
CASO_ESTADO_OFFSET EQU 0
CASO_USUARIO_OFFSET EQU 0
CASO_SIZE EQU 0

SEGMENTACION_CASOS0_OFFSET EQU 0
SEGMENTACION_CASOS1_OFFSET EQU 0
SEGMENTACION_CASOS2_OFFSET EQU 0
SEGMENTACION_SIZE EQU 0

ESTADISTICAS_CLT_OFFSET EQU 0
ESTADISTICAS_RBO_OFFSET EQU 0
ESTADISTICAS_KSC_OFFSET EQU 0
ESTADISTICAS_KDT_OFFSET EQU 0
ESTADISTICAS_ESTADO0_OFFSET EQU 0
ESTADISTICAS_ESTADO1_OFFSET EQU 0
ESTADISTICAS_ESTADO2_OFFSET EQU 0
ESTADISTICAS_SIZE EQU 0

global resolver_automaticamente

;void resolver_automaticamente(funcionCierraCasos* funcion, caso_t* arreglo_casos, caso_t* casos_a_revisar, int largo)
resolver_automaticamente:
    ret
