!classDefinition: #Atun category: #'Ejercicio 1'!
DenotativeObject subclass: #Atun
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 1'!


!classDefinition: #Lucy category: #'Ejercicio 1'!
DenotativeObject subclass: #Lucy
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 1'!


!classDefinition: #Pepe category: #'Ejercicio 1'!
DenotativeObject subclass: #Pepe
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Pepe class' category: #'Ejercicio 1'!
Pepe class
	instanceVariableNames: ''!

!Pepe class methodsFor: '-- all --' stamp: 'VM 3/20/2025 21:14:22'!
hola
^'chau'.! !
